apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJRzBjTTV4ZW5MQjB3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBMU1UUXhOelF4TkRoYUZ3MHpOakExTVRFeE56UTJORGhhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNnVkgzcU1ZM3A3VWdndURDMGRVUC9OM1dLS1doa0NnVDRtMVI5ek8xbHphL1NGOVphNzAyZ1F4YVAKU01FNytGV2RNYS9RNzNGeGU1d3BFZHNnM1JYUk94U3Vxb3MwUnFVb1AzNENPRThWbm5HRGpnOFFvaVJBaHEvQwo4Sms0WGhuMnVENDlrbUUwQ1FYT0tiN2JpYXFocytMMk9BcmdtWG5TYTd4cHFod2tTMGQrN2FkUGVVSWFCajJRCkppdHl3Q3dsRjI1WFM3UjhrQmVPYkd0bkIzOWw2OW9TcE9RN3dRTldBa0ZEL0thdlpwYWNIblk1STRGd1BpREMKbklqeXpxeTJWZWN4SERuOGpwSHliNG4zUlIrZ25GOW9MdVFtRysxMFZZQXN4U2VxZWVrZzhoQ0t2bkdvbHFJQwpCMC9xbG9aZWVJdVBEakhxNGpNZThvZlNYZ3E1QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUQ3VWV2theFFrYmxuODVBVkdyaUVVZFlZb3d6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ1R4ajFHd3lBdwpmMGtPNG1tWTNyVFdxckxMcVFXSmtsWUEyNXhxN0ttaFhXYUJMSlFmd1VOYVB4Skd5dnVVZE9nTkk0WUVPYmpjCmNBa1EwSTBRL21Sck11eHI0dFRsYzQyQnVnRWNsSXQxSEdNTS9xMU1LOTZWMGk1T0w1M2QxeHN4WnhhL1I0MmsKSEFKOUoxNklWZ2pIcjhudmxUTUdxNW0vaXBQNWVYR3pqWTF4MmFiUmF3dFZ5S0JnbnpSNVpsa2gvVGF2QkM5MAowUEo2dVV4c0xrMGlnNGJMY09PclY1ZzdLWGp5REhCQkI2R0hOQ0JHc0xSYmpqMmM4QXZRN1pQVVBqRWJlakFsCm4xVWlyd2xCYVcxQzI4NTJmRnkvQW93cDRVTDV4bXcxT05MMXowUTZBelEzYU9KSXc4Tm5KZ2hUbFl2QVdSaUQKL0ErYUNYL0E1eGtFCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://5CB19D538D4BCEE873E4D87BD84291EA.gr7.eu-west-1.eks.amazonaws.com
  name: dataops
contexts:
- context:
    cluster: dataops
    user: dataops
  name: dataops
current-context: dataops
kind: Config
preferences: {}
users:
- name: dataops
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws
      args:
        - eks
        - get-token
        - --cluster-name
        - dataops
