output "cluster_ca_certificate" {
  description = "Cluster CA certificate"
  value       = module.eks_cluster_dataops.cluster_ca_certificate
  sensitive   = true
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = module.eks_cluster_dataops.cluster_endpoint
}

output "cluster_name" {
  description = "The name of the cluster"
  value       = module.eks_cluster_dataops.cluster_name
}

output "cluster_security_group_id" {
  description = "Security group ID attached to the EKS cluster"
  value       = module.eks_cluster_dataops.cluster_security_group_id
}

output "kubeconfig" {
  description = "kubectl config as generated by the module"
  value       = module.eks_cluster_dataops.kubeconfig
  sensitive   = true
}