version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 804792415489.dkr.ecr.eu-west-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $ImageName -f ./Dockerfile .
      - docker tag $ImageName:latest 804792415489.dkr.ecr.eu-west-1.amazonaws.com/$ImageName:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 804792415489.dkr.ecr.eu-west-1.amazonaws.com/$ImageName:latest
env:
  variables:
    ImageName: "dataops-etl"