name: Terraform plan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"

      - name: Initalizing Terraform Code
        run: |
          echo Initalizing Terraform
          terraform init
          echo Initialiaation complete
          
      - name: Validating Terraform Code
        run: |
          echo Validating Terraform code
          terraform init
          echo Validation complete
          
      - name: Plan
        run: |
          echo Running Terraform plan
          terraform init
          echo Plan stage complete
